version: '3.8'

services:
 webapp:
  build: simple-webapp
  ports:
    - 49160:5000    
  image: ghofranesd/webapp-python
  restart: always
  depends_on:
    - bd
 bd:
  ports:
    - 3306:3306
  container_name: mydb  
  image: mysql
  environment:
    - MYSQL_DATABASE_USER=db_user
    - MYSQL_DATABASE_PASSWORD=Passw0rd
    - MYSQL_DATABASE_DB=employee_db
    - MYSQL_ALLOW_EMPTY_PASSWORD=1
  volumes:
    - mysql:/var/lib/mysql
    - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config: